fix(comer detail): style problem
comunion-io/comunion-front pull request #298
Opened 2022-06-18 08:29 UTC by l2xBrain

### What does this PR do? 一句话概括这次提交的内容

### All Submissions: 自检

- [ ] Have you done eslint + stylelint? 是否完成代码检查？
- [ ] Have you add necessary comments? 是否添加了必要的注释？
- [ ] Have you checked the business flow? 是否完成业务的自检？

2022-06-19 15:36 UTC, erguotou520 requested changes

2022-06-19 15:36 UTC, erguotou520 commented on packages/web/src/layouts/default/index.tsx
> +          <RouterView key={route.fullPath} />
这里为什么要加`key`?，没有什么意义？

2022-06-19 15:36 UTC, erguotou520 commented on packages/web/src/layouts/empty/index.tsx
> +    const route = useRoute()
同上

2022-06-19 15:36 UTC, erguotou520 commented on packages/web/src/pages/startup/detail/comer/components/ComerInfo/index.tsx
> +      router.replace({
为什么用`replace`而不是`push`？会导致路由丢失

2022-06-19 15:36 UTC, erguotou520 commented on packages/web/src/pages/startup/detail/comer/components/ComerInfo/index.tsx
> +            <div class={['u-h2 text-primary']}>{this.fansList?.length}</div>
`fanList`是否有分页而导致拿到的不是总数？

2022-06-19 15:36 UTC, erguotou520 commented on packages/web/src/pages/startup/detail/comer/components/ComerInfo/index.tsx
> +            <div class={['u-h2 text-success']}>{this.followList?.length}</div>
同上

2022-06-20 01:56 UTC, l2xBrain commented on packages/web/src/layouts/default/index.tsx
> +          <RouterView key={route.fullPath} />
vue-router 同一路由的跳转不会重新渲染， for example: startup/detail/comer/123 -> startup/detail/comer/456, 页面不会重新渲染

2022-06-20 01:58 UTC, l2xBrain commented on packages/web/src/pages/startup/detail/comer/components/ComerInfo/index.tsx
> +            <div class={['u-h2 text-primary']}>{this.fansList?.length}</div>
请求之前已拿到总数，请求的是全量数据

2022-06-20 02:09 UTC, l2xBrain commented on packages/web/src/pages/startup/detail/comer/components/ComerInfo/index.tsx
> +      router.replace({
已改为push

2022-06-20 02:19 UTC, erguotou520 requested changes

2022-06-20 02:19 UTC, erguotou520 commented on packages/web/src/layouts/default/index.tsx
> +          <RouterView key={route.fullPath} />
应该使用`watch`或者`onBeforeRouteUpdate`来处理，而不是给`RouterView` 加`key`
参考 https://router.vuejs.org/zh/guide/advanced/composition-api.html#%E5%9C%A8-setup-%E4%B8%AD%E8%AE%BF%E9%97%AE%E8%B7%AF%E7%94%B1%E5%92%8C%E5%BD%93%E5%89%8D%E8%B7%AF%E7%94%B1

2022-06-20 02:19 UTC, erguotou520 commented on packages/web/src/pages/startup/detail/comer/components/ComerInfo/index.tsx
> +            <div class={['u-h2 text-primary']}>{this.fansList?.length}</div>
那如果有上百个上千个关注者呢

2022-06-20 07:02 UTC, merged